language: go

go:
    - "1.9"
    - "1.10"
    - "1.11"
    - "1.12"

before_install:
    - go get github.com/gmallard/stompngo
    - go get github.com/hprose/hprose-golang
    - go get github.com/Shopify/sarama
    - go get github.com/bradfitz/gomemcache/memcache
    - go get gopkg.in/mgo.v2
    - go get github.com/streadway/amqp
    - go get github.com/go-redis/redis
    - go get github.com/syndtr/goleveldb/leveldb
    - go get github.com/kshvakov/clickhouse

install:
    - go get github.com/mattn/goveralls

script:
    - go test -v -covermode=count -coverprofile=coverage.out
    - go build Bifrost.go


after_success:
  - goveralls -coverprofile=full_cov.out -service=travis-ci