language: go

go:
    - "1.14"
    - "1.15"
    - "1.16"

before_install:
    - go get github.com/gmallard/stompngo
    - go get github.com/hprose/hprose-golang
    - go get github.com/Shopify/sarama
    - go get github.com/bradfitz/gomemcache/memcache
    - go get gopkg.in/mgo.v2
    - go get github.com/streadway/amqp
    - go get github.com/go-redis/redis/v8
    - go get github.com/syndtr/goleveldb/leveldb
    - go get github.com/ClickHouse/clickhouse-go
    - go get github.com/olivere/elastic/v7

install:
    - go get github.com/mattn/goveralls

script:
    - go test -v -covermode=count -coverprofile=coverage.out
    - ./build.sh travis


after_success:
  - goveralls -coverprofile=full_cov.out -service=travis-ci